// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbBKfZb2COxicT0kdY0SDgm541V6Q53dw',
    appId: '1:528127801498:web:6c91b4e9ba250eca654723',
    messagingSenderId: '528127801498',
    projectId: 'cenithos',
    authDomain: 'cenithos.firebaseapp.com',
    storageBucket: 'cenithos.firebasestorage.app',
    measurementId: 'G-JQXJBFLVX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD821aZ4zE2hiRu0Za4uHuEfBpdO2jNfQI',
    appId: '1:528127801498:android:3bfec7f8e327c47e654723',
    messagingSenderId: '528127801498',
    projectId: 'cenithos',
    storageBucket: 'cenithos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZTLZIDmNjR0njy8omoqus1qtbCOf0cY',
    appId: '1:528127801498:ios:7ce7031d33b6bdff654723',
    messagingSenderId: '528127801498',
    projectId: 'cenithos',
    storageBucket: 'cenithos.firebasestorage.app',
    androidClientId: '528127801498-u3bdoogphdt5qq3gq9jl24m686ns5sgt.apps.googleusercontent.com',
    iosClientId: '528127801498-s232hl6ingflg4hjpm9ku5k9ujlrsva3.apps.googleusercontent.com',
    iosBundleId: 'com.example.centhios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQZTLZIDmNjR0njy8omoqus1qtbCOf0cY',
    appId: '1:528127801498:ios:7ce7031d33b6bdff654723',
    messagingSenderId: '528127801498',
    projectId: 'cenithos',
    storageBucket: 'cenithos.firebasestorage.app',
    androidClientId: '528127801498-u3bdoogphdt5qq3gq9jl24m686ns5sgt.apps.googleusercontent.com',
    iosClientId: '528127801498-s232hl6ingflg4hjpm9ku5k9ujlrsva3.apps.googleusercontent.com',
    iosBundleId: 'com.example.centhios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbBKfZb2COxicT0kdY0SDgm541V6Q53dw',
    appId: '1:528127801498:web:f750691590db060c654723',
    messagingSenderId: '528127801498',
    projectId: 'cenithos',
    authDomain: 'cenithos.firebaseapp.com',
    storageBucket: 'cenithos.firebasestorage.app',
    measurementId: 'G-9X8XVMTBJS',
  );
}
