name: centhios
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  pinput: ^5.0.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  fl_chart: ^1.0.0
  uuid: ^4.4.2
  flutter_sms_inbox: ^1.0.4
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  dot_curved_bottom_nav: ^0.0.2
  workmanager: ^0.8.0
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
